Update launcher script and launchers
pypa/installer pull request #212
Opened 2024-01-24 02:30 UTC by Secrus

The previous version of the script was downloading launcher scripts from bitbucket, however, those were out of date. This changes the source for binaries to the latest `distlib` release from PyPI.

2024-01-24 02:37 UTC, bswck requested changes
🚀

2024-01-24 02:37 UTC, bswck commented on tools/update_launchers.py
> +    if paths := list(name for name in names if launcher in name):
```suggestion
    if paths := [name for name in names if launcher in name]:
```

2024-01-24 02:37 UTC, bswck commented on tools/update_launchers.py
> +        follow_redirects=True
```suggestion
        follow_redirects=True,
```

2024-01-24 02:37 UTC, bswck commented on tools/update_launchers.py
> +    with (tarfile.open(fileobj=io.BytesIO(distlib_tar)) as file):
```suggestion
    with tarfile.open(fileobj=io.BytesIO(distlib_tar)) as file:
```

2024-01-24 02:37 UTC, bswck commented on tools/update_launchers.py
> +    version = max((tuple(version_str.split(".") for version_str in json_response["versions"])))
```suggestion
    version = max(version_str.split(".") for version_str in json_response["versions"])
```
?

2024-11-01 20:50 UTC, pradyunsg approved these changes

2024-11-01 21:12 UTC, merged